# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '5.0'

    - name: Test
      run: go test -v ./...
      
    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -v -o linux_server ./cmd/server

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -v -o windows_server.exe ./cmd/server

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          linux_server
          windows_server.exe
        retention-days: 7
